Fetch cmp id from gpp string
AdaptMX/gpp pull request #9
Opened 2024-02-01 13:53 UTC by louiscb

2024-02-01 13:57 UTC, sneako requested changes

2024-02-01 13:57 UTC, sneako commented on lib/gpp/sections/tcfcav1/segment.ex
> +    {:ok, cmp_id, second_input} =
this will explode on invalid input. let's move the match on `{:ok, ...` in to the `with` statement

2024-02-01 14:26 UTC, louiscb commented on lib/gpp/sections/tcfcav1/segment.ex
> +    {:ok, cmp_id, second_input} =
I refactored it so that all three segments call the same function now to retrieve the fields

2024-02-01 16:55 UTC, nickjacob approved these changes
awesome

2024-02-02 09:54 UTC, sneako approved these changes

2024-02-02 09:54 UTC, merged